feature - search directories recursively
spatie/laravel-database-cleanup pull request #22
Opened 2019-05-23 10:43 UTC by wardhache

Added a flag in the config: 'model-cleanup.recursively'.

When this is set to 'true', all models in the specified directories *and* their subdirectories
will be cleaned if the models use the GetsCleanedUp interface.

When this is not specified in the config or set to 'false', only the models directly
underneath the specified directories will be cleaned.

2019-05-23 10:43 UTC, wardhache commented
See issue #21

2019-05-24 13:16 UTC, freekmurze requested changes

2019-05-24 13:16 UTC, freekmurze commented on README.md
> +    'recursively' => false,
Let's just do this by default. So you can remove this option.

2019-05-28 09:12 UTC, wardhache commented
I made the changes and it searches through the directories recursively. But the CI threw an error on PHP 7.3 saying: `The command "phpenv global 7.3" failed and exited with 1 during`.

2019-06-19 07:32 UTC, closed without merging